CALLBACKS:
  early_stopping:
    monitor: val_mse
    patience: 10
    mode: min
    min_delta: 0.0
  learning_rate_monitor:
    logging_interval: epoch
  model_checkpoint:
    filename: epoch={epoch}-val_mse={val_mse:.4f}
    mode: min
    monitor: val_mse
    save_top_k: 1

DATA:
  dataset_name: BKDDataset
  data_dir: /data/ouyangjiarui/hest/processhest
  disease_type: SKCM
  fold: 0
  gene_type: mean
  normalize: true
  cpm: true
  smooth: true
  num_genes: 50
  num_outputs: 50
  output_dir: output/pred/hest/SKCM/BKD_HEST
  test_dataloader:
    batch_size: 1
    num_workers: 4
    pin_memory: true
    shuffle: false
  val_dataloader:
    batch_size: 1
    num_workers: 4
    pin_memory: true
    shuffle: false
  train_dataloader:
    batch_size: 32
    num_workers: 4
    pin_memory: true
    shuffle: true

GENERAL:
  debug: false
  gpu: 3
  log_path: ./logs/hest/SKCM/MFBP
  seed: 2021

MODEL:
  model_name: 'MFBP'
  num_genes: 50
  num_outputs: 50
  feature_dim: 1024
  density_loss_weight: 0.1
  weight_path: /data/ouyangjiarui/hest/processhest/splits/SKCM/normalized_weights.json
  density_genes: []

TRAINING:
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 20
  mode: min
  monitor: val_mse
  lr_scheduler:
    factor: 0.5
    mode: min
    monitor: val_mse
    patience: 5
  gradient_clip_val: 1.0

defaults:
- ../base_config.yaml 